// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GroceryList.Entities
{
    internal partial class Customer
    {
        public Customer()
        {
            Orders = new HashSet<Order>();
        }

        [Key]
        public int CustomerID { get; set; }
        [Required (ErrorMessage ="Last Name is Required")]
        [StringLength(35, ErrorMessage ="Last Name is limited to 35 characters")]
        public string LastName { get; set; }
        [Required (ErrorMessage ="First Name is Required")]
        [StringLength(25, ErrorMessage ="First Name is Required")]
        public string FirstName { get; set; }
        [StringLength(30, ErrorMessage ="Address is limited to 30 characters" )]
        public string Address { get; set; }
        [StringLength(10, ErrorMessage ="Unit is limited to 10 characters")]
        public string Unit { get; set; }
        [StringLength(30, ErrorMessage ="City is limited to 30 characters")]
        public string City { get; set; }
        [StringLength(2, ErrorMessage ="Provices must be on their code with 2 characters")]
        public string Province { get; set; }
        [StringLength(12, ErrorMessage ="Phone number is limited to 12 characters")]
        public string Phone { get; set; }
        [StringLength(40, ErrorMessage ="Email is limited to 40 characters")]
        public string Email { get; set; }
        public int? PreferredStoreID { get; set; }

        [InverseProperty(nameof(Order.Customer))]
        public virtual ICollection<Order> Orders { get; set; }
    }
}