// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GroceryList.Entities
{
    internal partial class Store
    {
        public Store()
        {
            Orders = new HashSet<Order>();
            Pickers = new HashSet<Picker>();
        }

        [Key]
        public int StoreID { get; set; }
        [Required (ErrorMessage ="Location is required")]
        [StringLength(50, ErrorMessage ="Location is limited to 50 characters")]
        public string Location { get; set; }
        [Required (ErrorMessage ="Address is required")]
        [StringLength(30, ErrorMessage ="Address is limited to 30 characters")]
        public string Address { get; set; }
        [Required (ErrorMessage ="City is required")]
        [StringLength(30, ErrorMessage ="City is limited to 30 characters")]
        public string City { get; set; }
        [Required (ErrorMessage ="Provices is required")]
        [StringLength(2, ErrorMessage ="Provices is limited to 2 characters")]
        public string Province { get; set; }
        [Required (ErrorMessage ="Phone is required")]
        [StringLength(12, ErrorMessage ="Phone is limited to 12 characters")]
        public string Phone { get; set; }
        public Guid? ManagerID { get; set; }
        public Guid? AssistantManagerID { get; set; }
        [Column(TypeName = "image")]
        public byte[] Map { get; set; }

        [InverseProperty(nameof(Order.Store))]
        public virtual ICollection<Order> Orders { get; set; }
        [InverseProperty(nameof(Picker.Store))]
        public virtual ICollection<Picker> Pickers { get; set; }
    }
}